version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install lsb-release libgconf2-4 libnss3-1d libxss1 libappindicator1 libindicator7 xdg-utils
      - run: sudo apt-get install fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcups2 libgtk-3-0
      - run: curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - run: sudo dpkg -i google-chrome.deb
      - run: sudo apt-get install -f
      - run: sudo sed -i 's|HERE/chrome"|HERE/chrome" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
      - run: rm google-chrome.deb
      - run: curl https://install.meteor.com | /bin/sh
      - run: meteor npm install --save bcrypt
      - run: npm install
      - run: meteor npm run lint --silent
      - run: meteor test --once --driver-package dispatch:mocha-phantomjs
      - run: git submodule update --init
      - save_cache:
          key: meteor-lab-cci
          paths:
            - rm google-chrome.deb
            - ~/.npm
            - ~/.meteor